support PneumaticCraft Air port
ticticboooomer/MasterfulMachinery pull request #71
Opened 2024-06-13 15:34 UTC by nimeng1299

add PneumaticCraft air input/output
```
{
    "id": "pne_air_port",
    "controllerIds": "mm:pne",
    "name": "My Pne Air Port",
    "type": "mm:pneumaticcraft/air",
    "config": {
      "danger": 11.0,
      "critical": 15.0,
      "volume": 20000
    }
  }
 ```

support recipes for PneumaticCraft air
```
event.create("mm:my_process_recipe")
        .structureId("mm:pne_reactor2")
        .ticks(1)
        .input({
            type: "mm:input/consume",
            ingredient: {
                type: "mm:energy",
                amount: 1000
            }
        })
        .output({
            type: "mm:output/simple",
            ingredient: {
                type: "mm:pneumaticcraft/air",
                bar: 3.5,
                air: 100
            }
        })
    event.create("mm:my_process_recipe2")
        .structureId("mm:pne_reactor")
        .ticks(1)
        .input({
            type: "mm:input/consume",
            ingredient: {
                type: "mm:pneumaticcraft/air",
                bar: 3.5,
                air: 100
            }
        })
        .output({
            type: "mm:output/simple",
            ingredient: {
                type: "mm:energy",
                amount: 1000
            }
        })
```

2024-06-13 21:20 UTC, ticticboooomer requested changes
a Screen / GUI is needed
apply the model textures for the input and output ports. they are located in textures/block/compat_ports/pncr**

2024-06-14 11:01 UTC, ticticboooomer commented
awesome work thank you. just testing some last bits, then i will merge and update the documentation :)

2024-06-14 11:05 UTC, ticticboooomer approved these changes

2024-06-14 11:05 UTC, merged

2024-06-14 11:27 UTC, nimeng1299 commented
thank for pull request, bug gui seem has bug , `function render` to get `storage.getAir()` always return 0, now i try to fix it now